--- #YAML:1.0
name:                SystemTray-Applet-Gnome
version:             0.02
abstract:            Gnome support for SystemTray::Applet
license:             ~
author:              
    - Peter Sinnott <psinnott@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Gtk2::TrayIcon:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
